### ISSUE TITLE
Add more control on receiver acknowledgement

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-amqp-client#10]
Right now, the messages are automatically accepted when received. The consumer must be able to reject or manage the acknowledgment explicitly.

**Comment by barata0** [comment]
Thanks,

How may I reject the message?

**Comment by cescoffier** [comment]
with the master branch: `AMQPMessage.rejected()`

**Comment by cescoffier** [comment]
Fixed in master.
