### ISSUE TITLE
Method AmqpClient::createSender should have options parameter

### ISSUE THREAD

**Issue by dsimansk** [vert-x3/vertx-amqp-client#15]
@cescoffier 

I've noticed that there's no way to pass `AmqpSenderOptions` for cases when sender is create through `AmqpClient.createSender` directly. However, on the connection itself the method is present. IMO it'd be beneficial to have a uniform API for both cases.

https://github.com/vert-x3/vertx-amqp-client/blob/34cb868990a8ff87e5866991c7fa0585bdaac35c/src/main/java/io/vertx/amqp/AmqpClient.java#L127

https://github.com/vert-x3/vertx-amqp-client/blob/34cb868990a8ff87e5866991c7fa0585bdaac35c/src/main/java/io/vertx/amqp/AmqpConnection.java#L133-L135

Vs. receiver variant:
https://github.com/vert-x3/vertx-amqp-client/blob/34cb868990a8ff87e5866991c7fa0585bdaac35c/src/main/java/io/vertx/amqp/AmqpConnection.java#L81-L85

**Comment by cescoffier** [comment]
agreed
