### ISSUE TITLE
Missing modified method in the AMQPMessage class.

### ISSUE THREAD

**Issue by andrejpetras** [vert-x3/vertx-amqp-client#18]
The class AMQPMessage does not have a modified method.

http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#type-modified

Workaround:
```
io.vertx.amqp.AmqpMessage amqpMessage = message.getAmqpMessage().getDelegate();
Field field = AmqpMessageImpl.class.getDeclaredField("delivery");
field.setAccessible(true);
ProtonDelivery delivery = (ProtonDelivery) field.get(amqpMessage);
ProtonHelper.modified(delivery, settle, deliveryFailed, underliverableHere);
```

**Comment by cescoffier** [comment]
We should add it, however, @gemmellr told me it's rarely used. What's your use case?

**Comment by gemmellr** [comment]
Modified is used so I don't think that's what I would have said exactly.

**Comment by cescoffier** [comment]
Ok, so let's add it :-D

**Comment by cescoffier** [comment]
Method added to the 3.8 and master (4.0) branches

**Comment by andrejpetras** [comment]
Sorry for late answer. I am on the business trip right now. Thanks for adding the method.  With the  method "modified" you can modify the delivery-count of message. I believe this will help us to easily migrate the JMS application to AMQP ;)
