### ISSUE TITLE
The AmqpReceiver's message handler doesn't work after init by method createReceiver(...,Handler<AmqpMessage>, ..)

### ISSUE THREAD

**Issue by akoniar** [vert-x3/vertx-amqp-client#23]
I am created Amqp receiver with message's handler witch print a message to standard output.  After that I sended the message via Amqp sender with same address as receiver and the message didn't shows in standard output.
# Steps to reproduce:
1. Create receiver by AmqpClient method createReceiver(String address, AmqpReceiverOptions receiverOptions, Handler<AmqpMessage> messageHandler, Handler<AsyncResult<AmqpReceiver>> completionHandler).
The message handler is set to print a message to standard output.
The code:
```Java
AmqpClient client = AmqpClient.create(someClientOptions);
client.createReceiver(address,
      new AmqpReceiverOptions(),
      msg -> {
        System.out.println(msg.bodyAsString());
      },
      done -> {
          if(done.failed()){
            done.cause().printStackTrace();
          }
          System.out.println();
      });
```
2. Create sender with same address as client

3.1. Send some message with ack

3.2. Send some message without ack

# Excepted result:
Shows a message on the standard output
# Given result:
Message doesn't shown in standard output

# The problem
I found at version 3.8.1 the unused parameter "handler" 

https://github.com/vert-x3/vertx-amqp-client/blob/7f279474433379798dce2cbbc2328e543fa8b979/src/main/java/io/vertx/amqp/impl/AmqpConnectionImpl.java#L273-L296

In previous version it was used in constructor parameter of the AmqpReceiverImpl class to register a message's handler.

https://github.com/vert-x3/vertx-amqp-client/blob/ce3f4e0b02ec772b0fd1a2e9dc8d70aab97472be/src/main/java/io/vertx/amqp/impl/AmqpConnectionImpl.java#L273-L296

**Comment by vietj** [comment]
now you need to set the handler on the on the receiver explicitly.

**Comment by akoniar** [comment]
I know, but I excepted, when I use the method https://github.com/vert-x3/vertx-amqp-client/blob/ce3f4e0b02ec772b0fd1a2e9dc8d70aab97472be/src/main/java/io/vertx/amqp/impl/AmqpConnectionImpl.java#L273-L275

where I specified the message handler then the message handler should works, without any other setting up handler.

In other words. When I update from 3.8.0 (probably from earlier) to 3.8.1 then the message handler stop works.

And also the method in 3.8.1 behave the same as:
https://github.com/vert-x3/vertx-amqp-client/blob/ce3f4e0b02ec772b0fd1a2e9dc8d70aab97472be/src/main/java/io/vertx/amqp/impl/AmqpConnectionImpl.java#L267-L270
in 3.8.1

So I think it should be removed (Because it is a deprecated function it doesn't make any sense to repair it and it is redundant)

**Comment by vietj** [comment]
you are right, it should either be fixed or removed, Ithink we should remove it as you said. Are you interested providing a PR for this?

**Comment by akoniar** [comment]
Yes.

**Comment by vietj** [comment]
thanks for the contribution
