### ISSUE TITLE
NPE if connection goes down

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vert-x3/vertx-amqp-client#30]
I am simulating a connection error by creating a connection, then taking down my broker (on purpose) and continuing with the connection.  Instead of getting a graceful error about the connection being down I get an NPE. It traces back to this line in AmqpConnectionImpl.java

            sender = connection.get().createSender(address, opts); 

in method 
```
    public AmqpConnection createSender(String address, AmqpSenderOptions options,
        Handler<AsyncResult<AmqpSender>> completionHandler) {
```

I believe that all connection.get() calls in AmqpConnectionImpl.java be replaced by a method call that checks if the ProtonConnection is null and throws a graceful error if so.

**Comment by vietj** [comment]
can you provide a reproducer test ?

**Comment by UglyHobbitFeet** [comment]
You can use the example code at #28 

   `connection.rxCreateReceiver(address)` would cause it to barf if the broker is manually taken down between calls to the example method

**Comment by vietj** [comment]
@UglyHobbitFeet can you explain properly the steps for reproducing

**Comment by UglyHobbitFeet** [comment]
I can get into specifics later when I'm in front of a computer but I
basically have an amqp create Receiver working fine. I then manually do an
activemq stop command in a terminal to kill active mq. I then try to
send/receive another message and that's when I see the error

**Comment by UglyHobbitFeet** [comment]
I am using a verticle that holds an AmqpClient connection.  I then pass the connection to GraphQL/DataFetchers for sending/receiving Amqp messages.  As an example it looks something like this...

```
DataFetcher<CompletionStage<String>>send = env -> sendMessage(connection,
   env.getProperty("amqpAddress"), env.getProperty("message"));

DataFetcher<Publisher<Object>>receive = env -> receiveMessage(connection, 
  env.getProperty("amqpAddress"));

private CompletionStage<String> sendMessage(AmqpConnection con, 
  String address, String msg) {
  CompletableFuture<String> cf = new CompletableFuture<>();
  con.rxCreateSender(address)
    .otherRxOperators()
    .subscribe( ... eventually do a cf.complete(msg))
    // The otherRxOperators() are not relevant since it barfs on rxCreateSender)
  return cf;
}

private Publisher<Object> receiveMessage(AmqpConnection con, 
  String address) {
  return con.rxCreateReceiver(address)
    .otherRxOperators()
    .toFlowable(BackpressureStrategy.BUFFER) 
    // The otherRxOperators() are not relevant since it barfs on rxCreateReceiver)
}
```

Here are the steps to cause the error (Assuming we use example code like what is shown above.)
1. Make sure the AMQP broker is up (ex. cd /path-to-apachemq/bin; ./activemq start)
2. Make a GraphQL mutation to send a message (This calls the datafetcher which calls the sendMessage method shown above)
3. Make a GraphQL subscription to listen to messages (This calls the datafetcher which calls the receiveMessage method shown above)
4. Get back expected results (no barfing)
5. Leave the verticle running, but take down the broker (ex. cd /path-to-apachemq/bin; ./activemq stop)
6. Repeat step 2 by sending another message
7. NPE occurs due to connection.get() calls in the AmqpConnectionImpl class
