### ISSUE TITLE
`accepted`, `rejected`, `released` method must be call on the event loop

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-amqp-client#35]
Because proton-j expects these methods to be called on the event loop having created the message instance, the `accepted`, `rejected`, `released`.... methods must ensure that the right thread is used.

**Comment by vietj** [comment]
@cescoffier any news on this issue ?

**Comment by cescoffier** [comment]
No, I have a workaround, so feel free to remove the milestone

**Comment by vietj** [comment]
it will be bumped at release time I guess

**Comment by gemmellr** [comment]
To be clear, proton-j as a whole is single threaded, and essentially everything about a connection transport and its senders/recievers etc must happen on a single thread at a time. There is one outlier: as the proton-j message object is formed from bytes read from a delivery, the message object can sit on its own distinct from the others and be used by another thread at the same time (but is again itself single threaded).

The vertx-amqp-client message object wraps a proton-j message and delivery object. It is its use of the delivery that are not thread safe unless on the context, as they may occur while the context is doing other work for the connection (e.g recieving more messages to accept/release/other). I've raised #49 to have the updates always be  done on the context thread.
