### ISSUE TITLE
Message lost

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-amqp-client#37]
In some case a message can be lost, see https://github.com/vert-x3/vertx-amqp-client/commit/f6fd04b1167decf18802c04ffdb1f0c7275d7eb5

**Comment by ferhatsahinkaya** [comment]
This issue is same as https://github.com/vert-x3/vertx-amqp-client/issues/36

**Comment by vietj** [comment]
as said, do you know how to reproduce it ? it would help if you encountered this issue, otherwise we will try to find a way to reproduce it

**Comment by ferhatsahinkaya** [comment]
I think we can close this issue as the fix has been merged into both master and 3.9 branches. Thanks.

**Comment by vietj** [comment]
thank you for you contribution.
